// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAep8hS-1lCC3USxXeVfxkh1XUpvev8vZU',
    appId: '1:516632820170:web:9c3049b6c87c689ec13733',
    messagingSenderId: '516632820170',
    projectId: 'mooz-ec9f3',
    authDomain: 'mooz-ec9f3.firebaseapp.com',
    storageBucket: 'mooz-ec9f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHOMXuDdb9oN8kVdEQBMlg45OCJwdiGE',
    appId: '1:516632820170:android:c41f53b5ff5e880ec13733',
    messagingSenderId: '516632820170',
    projectId: 'mooz-ec9f3',
    storageBucket: 'mooz-ec9f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqnZbd63XV9xAn-LCYb9pE3xcLvaQCY8',
    appId: '1:516632820170:ios:b0bbf1a64c68561bc13733',
    messagingSenderId: '516632820170',
    projectId: 'mooz-ec9f3',
    storageBucket: 'mooz-ec9f3.appspot.com',
    androidClientId: '516632820170-bf4s9bceesnbi73p5mqmahto4f51kod2.apps.googleusercontent.com',
    iosClientId: '516632820170-vlgnpanemv79lsrm5080pm833tefa6p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mooz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqnZbd63XV9xAn-LCYb9pE3xcLvaQCY8',
    appId: '1:516632820170:ios:b0bbf1a64c68561bc13733',
    messagingSenderId: '516632820170',
    projectId: 'mooz-ec9f3',
    storageBucket: 'mooz-ec9f3.appspot.com',
    androidClientId: '516632820170-bf4s9bceesnbi73p5mqmahto4f51kod2.apps.googleusercontent.com',
    iosClientId: '516632820170-vlgnpanemv79lsrm5080pm833tefa6p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mooz',
  );
}
